### ISSUE TITLE
SSL Let's Encrypt

### ISSUE THREAD

**Issue by jujes** [dperson/owncloud#1]
Hi, I need use this container whit Let's Encrypt and Nginx proxy https://hub.docker.com/r/jwilder/nginx-proxy/
is possible?

**Comment by dperson** [comment]
This seems like it's much more an issue of using let's encrypt with the nginx proxy than it really has to do with the owncloud container...

Do you really want traffic to come in as SSL/TLS, be decrypted, be re-encrypted, then sent to owncloud, and decrypted again? That's going to add extra CPU overhead and latency...

I'd suggest contacting the nginx proxy maintainer.
